name: macOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Install deps
        run: |
          brew install coreutils cmake
          clang --version
          cmake --version
      - uses: actions/checkout@v1
      - name: Generate project files
        run: |
          cmake -S . -B build -D CMAKE_BUILD_TYPE=Release
      - name: Build
        run: |
          make -C build -j $(nproc)
      - name: Run test
        run: |
          ./build/Tests/libisdbtest
